set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER_ID GNU)
set(CMAKE_CXX_COMPILER_ID GNU)

set(TARGET_TRIPLET arm-none-eabi)

set(CMAKE_ASM_COMPILER ${TARGET_TRIPLET}-gcc)
set(CMAKE_C_COMPILER ${TARGET_TRIPLET}-gcc)
set(CMAKE_CXX_COMPILER ${TARGET_TRIPLET}-g++)
set(CMAKE_LINKER ${TARGET_TRIPLET}-g++)
set(CMAKE_OBJCOPY ${TARGET_TRIPLET}-objcopy)
set(CMAKE_SIZE ${TARGET_TRIPLET}-size)

set(CMAKE_EXECUTABLE_SUFFIX_C   .elf)
set(CMAKE_EXECUTABLE_SUFFIX_CXX .elf)
set(CMAKE_EXECUTABLE_SUFFIX_ASM .elf)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
